-- 14. Find the total number of couriers handled by each employee.  

SELECT e.Name, COUNT(c.CourierID) AS TotalNoOf_Couriers
FROM employee e
JOIN courier c ON e.courierID = c.courierID
GROUP BY e.EmployeeID, e.Name;

-- 15. Calculate the total revenue generated by each location

select l.locationID,l.locationName,sum(p.amount) as Total_Revenue
from payment p join location l
on p.locationID=l.locationID
group by l.locationID,l.LocationName;

-- 16. Find the total number of couriers delivered to each location.
  
select l.locationID,l.locationName, count(p.courierID)
from location l join payment p
on l.LocationID=p.LocationID
group by l.LocationID,l.LocationName;

-- 17. Find the courier with the highest average delivery time:  

SELECT c.CourierID, 
       AVG(DATEDIFF(DeliveryDate, PaymentDate)) AS AvgDeliveryTime
FROM Courier c join payment p on c.CourierID=p.PaymentID
group by c.CourierID
ORDER BY AvgDeliveryTime DESC LIMIT 1;

-- 18. Find Locations with Total Payments Less Than a Certain Amount 

select l.locationID,l.locationName,sum(p.amount) as Total_Revenue
from payment p join location l
on p.locationID=l.locationID
group by l.locationID,l.LocationName having Total_Revenue <3000;

-- 19. Calculate Total Payments per Location 

select l.locationID,l.locationName,count(p.amount) as Total_Revenue
from payment p join location l
on p.locationID=l.locationID
group by l.locationID,l.LocationName; 
 
 -- 20. Retrieve couriers who have received payments totaling more than $1000 in a specific location (LocationID = X):  

SELECT p.CourierID, SUM(p.Amount) AS TotalPayment
FROM Payment p JOIN Location l ON p.LocationID = l.LocationID
WHERE l.LocationID = 4
GROUP BY p.CourierID HAVING SUM(p.Amount) > 1000;

-- 21. Retrieve couriers who have received payments totaling more than $1000 after a certain date (PaymentDate > 'YYYY-MM-DD'):
  
 select courierID,sum(amount) as Total_Payment
 from payment where PaymentDate>'2025-02-20'
 group by courierID having sum(Amount)>1000;

-- 22. Retrieve locations where the total amount received is more than $5000 before a certain date (PaymentDate > 'YYYY-MM-DD')  

 select courierID,sum(amount) as Total_Payment
 from payment where PaymentDate<'2025-02-20'
 group by courierID having sum(Amount)>5000;
